name: Get User Orgs

on:
  workflow_dispatch:

jobs:
  get-orgs:
    runs-on: ubuntu-latest
    steps:
      - name: Get user orgs
        run: |
          curl --request GET \
               --url https://api.github.com/users/${{ github.actor }}/orgs \
               --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'accept: application/vnd.github.v3+json'
