name: Mirror and run GitLab CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Mirrror + trigger CI
      uses: lutengda/gitlab-mirror-and-ci-action@master
      with:
        args: "http://gitlab.cnosdb.com:8280/root/pr_test"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        LOCAL_GITHUB_REF: ${{ github.ref }}
        GITLAB_HOSTNAME: "43.247.178.238:8280"
        GITLAB_USERNAME: "root"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "9"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
